In [1]:
import numpy as np

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
def ale_vander_matrix(inpvector, n, increasing=False):
    
    if not increasing:
        out_matx = np.array([x**(n-1-i) for x in inpvector for i in range(n)]).reshape(inpvector.size,n)
    elif increasing:
        out_matx = np.array([x**i for x in inpvector for i in range(n)]).reshape(inpvector.size,n)
    
    return out_matx

print("------------OUTPUT-------------\n")

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 5
out_matx_dec_order = ale_vander_matrix(inputvector,no_col_opmat,False)
out_matx_inc_order = ale_vander_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Alexandre-Theophile Vandermonde matrix of the input array in decreasing order of powers:\n\n",out_matx_dec_order,"\n")
print("Alexandre-Theophile Vandermonde matrix of the input array in increasing order of powers:\n\n",out_matx_inc_order,"\n")

------------OUTPUT-------------

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 5 

Alexandre-Theophile Vandermonde matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Alexandre-Theophile Vandermonde matrix of the input array in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 



In [3]:
ale_vander_matrix(np.array([1,3,5,7,9]),4,False)

array([[  1,   1,   1,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [343,  49,   7,   1],
       [729,  81,   9,   1]])

In [4]:
ale_vander_matrix(np.array([1,3,5,7,9]),4,True)

array([[  1,   1,   1,   1],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125],
       [  1,   7,  49, 343],
       [  1,   9,  81, 729]])

Problem Statement 2

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
import numpy as np

def moving_average(input_array, k=3) :
    input_array_shape = input_array.shape[0]
    
    #Create a vector of zeroes with the shape as n-k+1
    
    out_array_moving_avg = np.zeros(input_array_shape - k + 1)
    
    # Iterate over the input array. While doing so, for every element, get the next k elements through slicing, 
    # computer their mean and add to the output array.
    
    for i in range(k, input_array_shape + 1):
        out_array_moving_avg[i-k] = input_array[i-k:i].mean()
    
    return out_array_moving_avg   


a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
win_size = 3
moving_average_arr = moving_average(a, win_size)

print("The input sequence is =", a, "\n")
print("The moving average of the sequence with the rolling window size", win_size, "is =\n", moving_average_arr, "\n")
print("The moving average sequence should have", a.shape[0] - win_size + 1, "values.\n")
print("The moving average sequence has", moving_average_arr.shape[0], "values.")

The input sequence is = [  3   5   7   2   8  10  11  65  72  81  99 100 150] 

The moving average of the sequence with the rolling window size 3 is =
 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333] 

The moving average sequence should have 11 values.

The moving average sequence has 11 values.
